### ISSUE TITLE
Configure linters

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#1]
Configure linters for JavaScript, CSS.  
Having .editorconfig would also be nice.

Use husky to setup a pre-commit hook to run the linters.

**Comment by abcdan** [comment]
I see, I'll look into this.

Next to that, are you talking about this one? https://github.com/typicode/husky
I was looking at it but have no clue what it is and how it works.

**Comment by taneltm** [comment]
Yup, it allows you to run something before it's committed or pushed.
So for example someone clones the repo, runs `npm install` husky hooks will be setup during install. Then one of the hooks could be to run code linters before commit (pre-commit).  
Then they change the code and before they push the code to git, the linters run automatically.

**Comment by SpyHoodle** [comment]
I'm pretty sure the linters are done now.
@abcdan I suggest this be closed.

**Comment by taneltm** [comment]
Nope. CSS linter isn’t there, but it could be that it’s not possible to add that anyway, cuz Svelte tooling isn’t that advanced.
