### ISSUE TITLE
Join and info buttons don't work on the home page

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#17]
After the intro text, there are two buttons the "Join us" and "Learn more", those buttons aren't working.

The `<button>` elements both have a `href` attribute which isn't valid HTML.

There are 3 options for fixing it:
1. Change the element to an anchor tag `<a href="...">`. When the same btn classes are applied, it will still look like a button, but the `href` link will work.
2. Keep the `<button>` element, remove `href` and add a click handler on the javascript side which navigate or open a new tab programmatically.

Ideally the anchor tag should be used for navigation and buttons should be used for interactivity on the same page, so I would go with the first option.

Also make sure the discord join page opens in a new window.

**Comment by anishanne** [comment]
I'll make a PR for it.

**Comment by SpyHoodle** [comment]
This issue has been fixed by @anishanne and should be closed.

**Comment by taneltm** [comment]
Not so fast. PR still has issues. Close it when the PR is merged.

**Comment by anishanne** [comment]
This issue can be closed as PR #19 has been merged.

**Comment by abcdan** [comment]
Will close! :sparkles:
