### ISSUE TITLE
Mixed tabs and spaces

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#2]
Various files have mixed tabs and spaces.
Looks like that might have been intentional, but usually when you configure the editor to use spaces for indentation, you can’t make the tab symbol anymore.

Also found that when you use tabs for indentation, there will be WAR!
But GitHub will also look at the `.editorconfig` file in the project root and will configure tab width based on what is set there.

https://stackoverflow.com/a/33831598

**Comment by abcdan** [comment]
I've noticed, will look at things!
