### ISSUE TITLE
Organise partners into BootStrap cards

### ISSUE THREAD

**Issue by SpyHoodle** [codedtogether/web#20]
I think putting the partners into different “cards” would make it look more organised and a lot nicer.

**Comment by abcdan** [comment]
I'll assign this one to Adam for now.

**Comment by SpyHoodle** [comment]
@abcdan Aww, I can do this right now if you want and make it look good (as in the partner page.)

**Comment by abcdan** [comment]
Of course you can try if you would like to make it, but assigned it to Adam to do it if nobody wanted to do it :P

**Comment by SpyHoodle** [comment]
Ok, i'll be doing it now.

**Comment by A-da-m** [comment]
Completed in PR #22 and #23
