### ISSUE TITLE
Unable to run NPM INSTALL in project root

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#3]
It's quite standard that `package.json` should be in project root for easy installation.  
Also the project has 2 `README.md` files and 2 `.gitignore` files.

Proposal:
- Rename `app/README.md` to `sapper-template.md` if this file is needed for reference.
- Merge `.gitignore` files
- Move everything from `/app` to `/` and delete the `/app` directory.

**Comment by abcdan** [comment]
I'll move it right away :)

**Comment by abcdan** [comment]
Check [this ](https://github.com/codedtogether/web/commit/4fc82cf80215d7ca3f340fb3f6bf52ff303fb00d)commit
