### ISSUE TITLE
Global CSS uses !important

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#32]
CSS means Cascading Style Sheets. When you use `!important` you break the cascading part.

**Comment by A-da-m** [comment]
It's to overwrite bootstrap styles.

**Comment by taneltm** [comment]
Unless bootstrap uses `!important` you can override the bootstrap styles by making your selector more specific.

**Comment by A-da-m** [comment]
The only places !important is used is spots where bootstrap is using it.

**Comment by taneltm** [comment]
Shouldn't be used anywhere IMO.
Some reading https://github.com/CSSLint/csslint/wiki/Disallow-!important - check the links at the bottom for more.

**Comment by abcdan** [comment]
I don't think this should be a real issue, for now, I'm just reading about it but I don't think it breaks anything.

**Comment by taneltm** [comment]
No it doesn't break anything. It's a low priority refactoring.
But I've been in projects where this has grown into a bigger issue.

**Comment by A-da-m** [comment]
We are only using `!important` for important bootstrap color overwrites. If it becomes a bigger issue thats for another day.
