### ISSUE TITLE
Merge the Home, About and Discord pages into one page

### ISSUE THREAD

**Issue by taneltm** [codedtogether/web#5]
Right now the Home and About pages are a bit redundant.  
Also the whole community revolves around the code::together discord server, so information about it should be prominent on the home page.

All three pages should be merged.

**Comment by abcdan** [comment]
I'll replace the Discord page with a direct URL to the server.

And merge the two other pages.

**Comment by abcdan** [comment]
Done!

**Comment by taneltm** [comment]
Good enough for now. But generally having an external link in navigation bar is bad UX.

**Comment by abcdan** [comment]
I agree, but on the other hand we are currently a community based on a Discord server.

**Comment by taneltm** [comment]
Later when the join button is on the home page, the discord link in navigation bar would be redundant. But yeah we can’t remove it yet.

**Comment by abcdan** [comment]
That's what I was thinking about as well or a button on the top right of the menu.

I'll try to build some sort of design for the website/theme we can use for the rest of it as well.

**Comment by abcdan** [comment]
We've done this, closing again for now.
